server:
  port: 12001
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10001/eureka
  instance:
    prefer-ip-address: true
spring:
  application:
    name: medical-gateway
  cloud:
    gateway:
      routes:
        - id: medical-order-service
          uri: lb://medical-order-service
          predicates:
            - Path=/order/**
          filters:
            - StripPrefix=1